'use client';

/**
 * GenerateSummaryDialog Component (Story P4-4.5)
 *
 * Dialog for generating on-demand activity summaries for custom time periods.
 *
 * AC Coverage:
 * - AC6: "Generate Summary" button/dialog on summaries page
 * - AC7: Time period dropdown (Last 1 hour, Last 3 hours, etc.)
 * - AC8: Custom time period with date/time picker
 * - AC9: Loading state with progress indicator
 * - AC10: Error state with user-friendly message
 * - AC11: Generated summary displays in dialog with stats
 * - AC12: Save to history functionality (automatic on generation)
 */

import { useState, useCallback } from 'react';
import { format, subHours } from 'date-fns';
import { parseApiDate } from '@/lib/datetime';
import {
  Sparkles,
  Clock,
  Activity,
  Camera,
  AlertTriangle,
  Bell,
  Users,
  Car,
  Loader2,
  AlertCircle,
  CheckCircle2,
  CalendarIcon,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { useGenerateSummary, SummaryGenerateResponse } from '@/hooks/useSummaries';

/** Time period options for the dropdown (AC7) */
const TIME_PERIOD_OPTIONS = [
  { value: '1', label: 'Last 1 hour' },
  { value: '3', label: 'Last 3 hours' },
  { value: '6', label: 'Last 6 hours' },
  { value: '12', label: 'Last 12 hours' },
  { value: '24', label: 'Last 24 hours' },
  { value: 'custom', label: 'Custom range' },
] as const;

type TimePeriodValue = typeof TIME_PERIOD_OPTIONS[number]['value'];

/**
 * StatItem - Compact stat display for generated summary
 */
function StatItem({
  icon: Icon,
  label,
  value,
}: {
  icon: React.ElementType;
  label: string;
  value: number;
}) {
  return (
    <div className="flex items-center gap-2">
      <Icon className="h-4 w-4 text-muted-foreground" />
      <span className="text-sm">
        <span className="font-medium">{value}</span>{' '}
        <span className="text-muted-foreground">{label}</span>
      </span>
    </div>
  );
}

/**
 * SummaryResult - Display generated summary (AC11)
 */
function SummaryResult({ summary }: { summary: SummaryGenerateResponse }) {
  const periodStart = parseApiDate(summary.period_start)!;
  const periodEnd = parseApiDate(summary.period_end)!;

  return (
    <div className="space-y-4">
      {/* Success indicator */}
      <Alert className="border-green-200 bg-green-50 dark:bg-green-950/20">
        <CheckCircle2 className="h-4 w-4 text-green-600" />
        <AlertTitle className="text-green-800 dark:text-green-200">Summary Generated</AlertTitle>
        <AlertDescription className="text-green-700 dark:text-green-300">
          {format(periodStart, 'MMM d, h:mm a')} - {format(periodEnd, 'h:mm a')}
        </AlertDescription>
      </Alert>

      {/* Stats grid */}
      <Card>
        <CardContent className="pt-4">
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
            <StatItem icon={Activity} label="events" value={summary.event_count} />
            <StatItem icon={Camera} label="cameras" value={summary.camera_count} />
            <StatItem icon={AlertTriangle} label="alerts" value={summary.alert_count} />
            <StatItem icon={Bell} label="doorbells" value={summary.doorbell_count} />
            <StatItem icon={Users} label="people" value={summary.person_count} />
            <StatItem icon={Car} label="vehicles" value={summary.vehicle_count} />
          </div>
        </CardContent>
      </Card>

      {/* Summary text */}
      <div className="rounded-lg border bg-muted/30 p-4">
        <p className="text-sm leading-relaxed">{summary.summary_text}</p>
      </div>

      {/* Generation info */}
      <p className="text-xs text-muted-foreground text-center">
        Generated by {summary.provider_used || 'AI'} • Saved to history
      </p>
    </div>
  );
}

/**
 * Main GenerateSummaryDialog Component
 */
export function GenerateSummaryDialog() {
  const [isOpen, setIsOpen] = useState(false);
  const [timePeriod, setTimePeriod] = useState<TimePeriodValue>('3');
  const [customStartDate, setCustomStartDate] = useState('');
  const [customStartTime, setCustomStartTime] = useState('');
  const [customEndDate, setCustomEndDate] = useState('');
  const [customEndTime, setCustomEndTime] = useState('');
  const [generatedSummary, setGeneratedSummary] = useState<SummaryGenerateResponse | null>(null);

  const generateMutation = useGenerateSummary();

  const isCustomRange = timePeriod === 'custom';

  // Reset state when dialog closes
  const handleOpenChange = useCallback((open: boolean) => {
    setIsOpen(open);
    if (!open) {
      // Reset state when closing
      setTimePeriod('3');
      setCustomStartDate('');
      setCustomStartTime('');
      setCustomEndDate('');
      setCustomEndTime('');
      setGeneratedSummary(null);
      generateMutation.reset();
    }
  }, [generateMutation]);

  // Set default custom dates when custom is selected
  const handleTimePeriodChange = useCallback((value: string) => {
    setTimePeriod(value as TimePeriodValue);
    if (value === 'custom') {
      // Default to last 3 hours for custom
      const now = new Date();
      const threeHoursAgo = subHours(now, 3);
      setCustomStartDate(format(threeHoursAgo, 'yyyy-MM-dd'));
      setCustomStartTime(format(threeHoursAgo, 'HH:mm'));
      setCustomEndDate(format(now, 'yyyy-MM-dd'));
      setCustomEndTime(format(now, 'HH:mm'));
    }
  }, []);

  // Generate summary handler
  const handleGenerate = useCallback(async () => {
    try {
      let result: SummaryGenerateResponse;

      if (isCustomRange) {
        // Custom range mode - send start_time and end_time
        const startDateTime = new Date(`${customStartDate}T${customStartTime}`);
        const endDateTime = new Date(`${customEndDate}T${customEndTime}`);

        result = await generateMutation.mutateAsync({
          start_time: startDateTime.toISOString(),
          end_time: endDateTime.toISOString(),
        });
      } else {
        // Hours back mode
        result = await generateMutation.mutateAsync({
          hours_back: parseInt(timePeriod, 10),
        });
      }

      setGeneratedSummary(result);
    } catch (error) {
      // Error is handled by mutation state
      console.error('Failed to generate summary:', error);
    }
  }, [isCustomRange, customStartDate, customStartTime, customEndDate, customEndTime, timePeriod, generateMutation]);

  // Validate custom range
  const isCustomRangeValid = useCallback(() => {
    if (!isCustomRange) return true;
    if (!customStartDate || !customStartTime || !customEndDate || !customEndTime) return false;

    const startDateTime = new Date(`${customStartDate}T${customStartTime}`);
    const endDateTime = new Date(`${customEndDate}T${customEndTime}`);
    return endDateTime > startDateTime;
  }, [isCustomRange, customStartDate, customStartTime, customEndDate, customEndTime]);

  const canGenerate = !generateMutation.isPending && (!isCustomRange || isCustomRangeValid());

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <Button variant="default" className="gap-2">
          <Sparkles className="h-4 w-4" />
          Generate Summary
        </Button>
      </DialogTrigger>

      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5" />
            Generate Activity Summary
          </DialogTitle>
          <DialogDescription>
            Generate an AI-powered summary of camera activity for a specific time period.
          </DialogDescription>
        </DialogHeader>

        {/* Show result if generated */}
        {generatedSummary ? (
          <SummaryResult summary={generatedSummary} />
        ) : (
          <div className="space-y-4 py-4">
            {/* Time period selection (AC7) */}
            <div className="space-y-2">
              <Label htmlFor="time-period">Time Period</Label>
              <Select value={timePeriod} onValueChange={handleTimePeriodChange}>
                <SelectTrigger id="time-period">
                  <SelectValue placeholder="Select time period" />
                </SelectTrigger>
                <SelectContent>
                  {TIME_PERIOD_OPTIONS.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      {option.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Custom date/time pickers (AC8) */}
            {isCustomRange && (
              <div className="space-y-4 rounded-lg border p-4 bg-muted/30">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Start Date</Label>
                    <div className="relative">
                      <CalendarIcon className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                      <Input
                        type="date"
                        value={customStartDate}
                        onChange={(e) => setCustomStartDate(e.target.value)}
                        className="pl-10"
                      />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <Label>Start Time</Label>
                    <div className="relative">
                      <Clock className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                      <Input
                        type="time"
                        value={customStartTime}
                        onChange={(e) => setCustomStartTime(e.target.value)}
                        className="pl-10"
                      />
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>End Date</Label>
                    <div className="relative">
                      <CalendarIcon className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                      <Input
                        type="date"
                        value={customEndDate}
                        onChange={(e) => setCustomEndDate(e.target.value)}
                        className="pl-10"
                      />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <Label>End Time</Label>
                    <div className="relative">
                      <Clock className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                      <Input
                        type="time"
                        value={customEndTime}
                        onChange={(e) => setCustomEndTime(e.target.value)}
                        className="pl-10"
                      />
                    </div>
                  </div>
                </div>

                {/* Validation message */}
                {!isCustomRangeValid() && customStartDate && customEndDate && (
                  <p className="text-xs text-destructive">
                    End time must be after start time
                  </p>
                )}
              </div>
            )}

            {/* Error state (AC10) */}
            {generateMutation.isError && (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertTitle>Generation Failed</AlertTitle>
                <AlertDescription>
                  {generateMutation.error instanceof Error
                    ? generateMutation.error.message
                    : 'Unable to generate summary. Please try again.'}
                </AlertDescription>
              </Alert>
            )}
          </div>
        )}

        <DialogFooter>
          {generatedSummary ? (
            <Button variant="outline" onClick={() => handleOpenChange(false)}>
              Close
            </Button>
          ) : (
            <>
              <Button variant="outline" onClick={() => handleOpenChange(false)}>
                Cancel
              </Button>
              <Button
                onClick={handleGenerate}
                disabled={!canGenerate}
                className="gap-2"
              >
                {/* Loading state (AC9) */}
                {generateMutation.isPending ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" />
                    Generate
                  </>
                )}
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default GenerateSummaryDialog;
